name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 src/*.py --max-line-length=120

      - name: Run tests (if any)
        run: |
          echo "No tests implemented yet"

      - name: Build Docker image
        run: |
          docker build -t iris-fastapi .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Tag Docker image (latest)
        run: docker tag iris-fastapi docker.io/djana22/iris-fastapi:latest

      - name: Push Docker image (latest)
        run: docker push docker.io/djana22/iris-fastapi:latest
